# SQL Python connect

In [1]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [2]:
engine1 = create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [3]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [4]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students

In [8]:
q('select * from emp')

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1235  KHULAN    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [10]:
q('select * from dept')

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [17]:
# List the names of analysts and salesmen
q('select ename, job from emp where job in ("Analyst","Salesman")')

    ename       job
0  DHIRAJ   ANALYST
1  KHULAN   ANALYST
2   ALLEN  SALESMAN
3    WARD  SALESMAN
4  MARTIN  SALESMAN
5   SCOTT   ANALYST
6  TURNER  SALESMAN
7    FORD   ANALYST

In [20]:
# List details of employees who have joined before 30 Sep 81.
q('select ename, hiredate from emp where hiredate < "1981-09-30"')

    ename    hiredate
0   SMITH  1980-12-17
1   ALLEN  1981-02-20
2    WARD  1981-02-22
3   JONES  1981-04-02
4  MARTIN  1981-09-28
5   BLAKE  1981-05-01
6   CLARK  1981-06-09
7  TURNER  1981-09-08

In [24]:
# List names of employees who are not managers. (! command = not equal )
q('select ename, job from emp where job != "MANAGER"')

     ename        job
0   DHIRAJ    ANALYST
1   KHULAN    ANALYST
2    SMITH      CLERK
3    ALLEN   SALESMAN
4     WARD   SALESMAN
5   MARTIN   SALESMAN
6    SCOTT    ANALYST
7     KING  PRESIDENT
8   TURNER   SALESMAN
9    ADAMS      CLERK
10   JAMES      CLERK
11    FORD    ANALYST
12  MILLER      CLERK

In [28]:
# List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.
# using IN command = is same 
q('select ename, empno from emp where empno IN (7369,7521, 7839, 7934, 7788)')

    ename  empno
0   SMITH   7369
1    WARD   7521
2   SCOTT   7788
3    KING   7839
4  MILLER   7934

In [32]:
# List employees not belonging to department 30, 40, or 10.
q('select ename, deptno from emp where deptno not in (30,40,10)')

    ename  deptno
0  KHULAN      20
1   SMITH      20
2   JONES      20
3   SCOTT      20
4   ADAMS      20
5    FORD      20

In [33]:
# List employee names for those who have joined between 30 June and 31 Dec. ‘81.
q('select ename, hiredate from emp where hiredate between "1981-06-30" and "1981-12-31"')

    ename    hiredate
0  MARTIN  1981-09-28
1    KING  1981-11-17
2  TURNER  1981-09-08
3   JAMES  1981-12-03
4    FORD  1981-12-03

In [35]:
# List the different designations in the company.
q('select distinct job from emp')

         job
0    ANALYST
1      CLERK
2   SALESMAN
3    MANAGER
4  PRESIDENT